### ISSUE TITLE
Cannot give 8-character filename

### ISSUE THREAD

**Issue by ht-deko** [ffxx68/Sharp_ce140f_emul#1]
If an 8-character filename is used, the SAVE command will fail to execute.
It seems to be caused by the small buffer size of FileName defined in `commands.cpp`.

```
// locals
uint8_t  out_checksum = 0;
FILE    *fp;
int      fileCount; 
uint8_t  FileName[17]; // [15] -> [17]
int      file_size;
int      file_pos = 0;
```

**Comment by ffxx68** [comment]
Thanks for the pointer! I'm curious - where are you testing this code on? Have you built a board yourself, by chance?

**Comment by ht-deko** [comment]
I am testing on a CE-140F emulator built on a breadboard.
https://ht-deko.com/pokecom/ce140f_emu.html

**Comment by ffxx68** [comment]
Great ! I'm glad to see you have managed to reproduce the project, and fix
some bugs as well !

Il giorno gio 23 mar 2023 alle ore 03:10 DEKO ***@***.***> ha
scritto:
