### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by phoen1s** [ffxx68/Sharp_ce140f_emul#5]
i download bin file from here:
https://github.com/ffxx68/Sharp_ce140f_emul/releases
but wheni copy onto the board they make 1 file whit name FAIL.txt and this inside:
The application file format is unknown and cannot be parsed and/or processed.
can you help me please?
thanks.

**Comment by hagedornj** [comment]
Hi I have started to port the code to PCB version 2.0. Concerning the pcb  I have some comments/improvements. But at the moment I can download code and the function looks OK. Concerning the source code I found some problems:
inDataBuf and OutDataBuf are not declared. What size do you selected? The function: ProcessCommand() is missing.
Many thanks
Joerg

**Comment by ffxx68** [comment]
> i download bin file from here: https://github.com/ffxx68/Sharp_ce140f_emul/releases but wheni copy onto the board they make 1 file whit name FAIL.txt and this inside: The application file format is unknown and cannot be parsed and/or processed. can you help me please? thanks.

That's the .bin file which should be uploaded to the board using the virtual drive which appears as soon as you plug it the USB of a PC. I make with a Windows PC. Not sure about the details with a Linux, but I guess it should be the same. When you plug the board the your PC, do you have a new virtual drive and you upload the .bin file there?

**Comment by ffxx68** [comment]
> Hi I have started to port the code to PCB version 2.0. Concerning the pcb I have some comments/improvements. But at the moment I can download code and the function looks OK. Concerning the source code I found some problems: inDataBuf and OutDataBuf are not declared. What size do you selected? The function: ProcessCommand() is missing. Many thanks Joerg

Very glad to know you're working on PCB version 2! As you might have noticed, there's some work needed at software level too, to use this changed hardware structure. Pinout used are different!
With respect to buffer size, it's defined in commands.h:
```// communication data depth (max file size during LOAD)
#if defined TARGET_NUCLEO_L432KC
#define OUT_BUF_SIZE 20000
#define IN_BUF_SIZE 1000
#endif
#if defined TARGET_NUCLEO_L053R8
#define OUT_BUF_SIZE 256
#define IN_BUF_SIZE 256
#endif
```

**Comment by ffxx68** [comment]
Closing this for the timebeing. Further questions, please raise a new issue.
